/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ArizaDurumu = IDL.Variant({
  'acik' : IDL.Null,
  'kapali' : IDL.Null,
});
export const Ariza = IDL.Record({
  'arizaId' : IDL.Text,
  'baslik' : IDL.Text,
  'olusturmaZamani' : Time,
  'aciklama' : IDL.Text,
  'olusturanPrincipal' : IDL.Principal,
  'daireId' : IDL.Text,
  'durum' : ArizaDurumu,
  'binaId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Daire = IDL.Record({
  'olusturmaTarihi' : Time,
  'daireId' : IDL.Text,
  'binaId' : IDL.Nat,
  'daireAdi' : IDL.Text,
});
export const Role = IDL.Variant({
  'yetkili' : IDL.Null,
  'sakin' : IDL.Null,
  'binaSahibi' : IDL.Null,
});
export const Duyuru = IDL.Record({
  'olusturmaTarihi' : Time,
  'baslik' : IDL.Text,
  'duyuruId' : IDL.Text,
  'aciklama' : IDL.Text,
  'olusturanPrincipal' : IDL.Principal,
  'binaId' : IDL.Nat,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'loginCount' : IDL.Nat,
  'firstLogin' : Time,
  'lastLogin' : Time,
  'daireId' : IDL.Opt(IDL.Text),
  'binaId' : IDL.Opt(IDL.Nat),
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Bina = IDL.Record({
  'olusturulmaTarihi' : Time,
  'binaAdi' : IDL.Text,
  'olusturanPrincipal' : IDL.Principal,
  'binaId' : IDL.Nat,
});
export const UserProfil = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : Role,
  'loginCount' : IDL.Nat,
  'firstLogin' : Time,
  'lastLogin' : Time,
  'daireId' : IDL.Opt(IDL.Text),
  'binaId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'arizaBildir' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Ariza], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'binaOlustur' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'daireOlustur' : IDL.Func([IDL.Text], [IDL.Text], []),
  'daireleriListele' : IDL.Func([], [IDL.Vec(Daire)], ['query']),
  'davetKoduOlustur' : IDL.Func([Role], [IDL.Text], []),
  'duyuruOlustur' : IDL.Func([IDL.Text, IDL.Text], [Duyuru], []),
  'duyurulariListele' : IDL.Func([], [IDL.Vec(Duyuru)], ['query']),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'kullaniciBinasiniGetir' : IDL.Func([], [IDL.Opt(Bina)], ['query']),
  'kullanicilariListele' : IDL.Func([], [IDL.Vec(UserProfil)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ArizaDurumu = IDL.Variant({ 'acik' : IDL.Null, 'kapali' : IDL.Null });
  const Ariza = IDL.Record({
    'arizaId' : IDL.Text,
    'baslik' : IDL.Text,
    'olusturmaZamani' : Time,
    'aciklama' : IDL.Text,
    'olusturanPrincipal' : IDL.Principal,
    'daireId' : IDL.Text,
    'durum' : ArizaDurumu,
    'binaId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Daire = IDL.Record({
    'olusturmaTarihi' : Time,
    'daireId' : IDL.Text,
    'binaId' : IDL.Nat,
    'daireAdi' : IDL.Text,
  });
  const Role = IDL.Variant({
    'yetkili' : IDL.Null,
    'sakin' : IDL.Null,
    'binaSahibi' : IDL.Null,
  });
  const Duyuru = IDL.Record({
    'olusturmaTarihi' : Time,
    'baslik' : IDL.Text,
    'duyuruId' : IDL.Text,
    'aciklama' : IDL.Text,
    'olusturanPrincipal' : IDL.Principal,
    'binaId' : IDL.Nat,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'loginCount' : IDL.Nat,
    'firstLogin' : Time,
    'lastLogin' : Time,
    'daireId' : IDL.Opt(IDL.Text),
    'binaId' : IDL.Opt(IDL.Nat),
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Bina = IDL.Record({
    'olusturulmaTarihi' : Time,
    'binaAdi' : IDL.Text,
    'olusturanPrincipal' : IDL.Principal,
    'binaId' : IDL.Nat,
  });
  const UserProfil = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : Role,
    'loginCount' : IDL.Nat,
    'firstLogin' : Time,
    'lastLogin' : Time,
    'daireId' : IDL.Opt(IDL.Text),
    'binaId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'arizaBildir' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Ariza], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'binaOlustur' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'daireOlustur' : IDL.Func([IDL.Text], [IDL.Text], []),
    'daireleriListele' : IDL.Func([], [IDL.Vec(Daire)], ['query']),
    'davetKoduOlustur' : IDL.Func([Role], [IDL.Text], []),
    'duyuruOlustur' : IDL.Func([IDL.Text, IDL.Text], [Duyuru], []),
    'duyurulariListele' : IDL.Func([], [IDL.Vec(Duyuru)], ['query']),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'kullaniciBinasiniGetir' : IDL.Func([], [IDL.Opt(Bina)], ['query']),
    'kullanicilariListele' : IDL.Func([], [IDL.Vec(UserProfil)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };