/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bina {
  'olusturulmaTarihi' : Time,
  'binaAdi' : string,
  'olusturanPrincipal' : Principal,
  'binaId' : bigint,
}
export interface DavetKodu {
  'kod' : string,
  'rol' : Role,
  'olusturmaTarihi' : Time,
  'kullanildiMi' : boolean,
  'kullananPrincipal' : [] | [Principal],
  'olusturanPrincipal' : Principal,
  'kullanimTarihi' : [] | [Time],
  'binaId' : bigint,
}
export type Role = { 'yetkili' : null } |
  { 'sakin' : null } |
  { 'binaSahibi' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'loginCount' : bigint,
  'firstLogin' : Time,
  'lastLogin' : Time,
  'binaId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'binaOlustur' : ActorMethod<[string], bigint>,
  'davetKodlariniListele' : ActorMethod<[], Array<DavetKodu>>,
  'davetKoduIleKayitOl' : ActorMethod<[string], string>,
  'davetKoduOlustur' : ActorMethod<[Role], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'kullaniciBinasiniGetir' : ActorMethod<[], [] | [Bina]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];