/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'yetkili' : IDL.Null,
  'sakin' : IDL.Null,
  'binaSahibi' : IDL.Null,
});
export const Time = IDL.Int;
export const DavetKodu = IDL.Record({
  'kod' : IDL.Text,
  'rol' : Role,
  'olusturmaTarihi' : Time,
  'kullanildiMi' : IDL.Bool,
  'kullananPrincipal' : IDL.Opt(IDL.Principal),
  'olusturanPrincipal' : IDL.Principal,
  'kullanimTarihi' : IDL.Opt(Time),
  'binaId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'loginCount' : IDL.Nat,
  'firstLogin' : Time,
  'lastLogin' : Time,
  'binaId' : IDL.Opt(IDL.Nat),
});
export const Bina = IDL.Record({
  'olusturulmaTarihi' : Time,
  'binaAdi' : IDL.Text,
  'olusturanPrincipal' : IDL.Principal,
  'binaId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'binaOlustur' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'davetKodlariniListele' : IDL.Func([], [IDL.Vec(DavetKodu)], ['query']),
  'davetKoduIleKayitOl' : IDL.Func([IDL.Text], [IDL.Text], []),
  'davetKoduOlustur' : IDL.Func([Role], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'kullaniciBinasiniGetir' : IDL.Func([], [IDL.Opt(Bina)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'yetkili' : IDL.Null,
    'sakin' : IDL.Null,
    'binaSahibi' : IDL.Null,
  });
  const Time = IDL.Int;
  const DavetKodu = IDL.Record({
    'kod' : IDL.Text,
    'rol' : Role,
    'olusturmaTarihi' : Time,
    'kullanildiMi' : IDL.Bool,
    'kullananPrincipal' : IDL.Opt(IDL.Principal),
    'olusturanPrincipal' : IDL.Principal,
    'kullanimTarihi' : IDL.Opt(Time),
    'binaId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'loginCount' : IDL.Nat,
    'firstLogin' : Time,
    'lastLogin' : Time,
    'binaId' : IDL.Opt(IDL.Nat),
  });
  const Bina = IDL.Record({
    'olusturulmaTarihi' : Time,
    'binaAdi' : IDL.Text,
    'olusturanPrincipal' : IDL.Principal,
    'binaId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'binaOlustur' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'davetKodlariniListele' : IDL.Func([], [IDL.Vec(DavetKodu)], ['query']),
    'davetKoduIleKayitOl' : IDL.Func([IDL.Text], [IDL.Text], []),
    'davetKoduOlustur' : IDL.Func([Role], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'kullaniciBinasiniGetir' : IDL.Func([], [IDL.Opt(Bina)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };