/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ariza {
  'arizaId' : string,
  'baslik' : string,
  'olusturmaZamani' : Time,
  'aciklama' : string,
  'olusturanPrincipal' : Principal,
  'daireId' : string,
  'durum' : ArizaDurumu,
  'binaId' : bigint,
}
export type ArizaDurumu = { 'acik' : null } |
  { 'kapali' : null };
export interface Bina {
  'olusturulmaTarihi' : Time,
  'binaAdi' : string,
  'olusturanPrincipal' : Principal,
  'binaId' : bigint,
}
export interface Daire {
  'olusturmaTarihi' : Time,
  'daireId' : string,
  'binaId' : bigint,
  'daireAdi' : string,
}
export interface Duyuru {
  'olusturmaTarihi' : Time,
  'baslik' : string,
  'duyuruId' : string,
  'aciklama' : string,
  'olusturanPrincipal' : Principal,
  'binaId' : bigint,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Role = { 'yetkili' : null } |
  { 'sakin' : null } |
  { 'binaSahibi' : null };
export type Time = bigint;
export interface UserProfil {
  'principal' : Principal,
  'name' : string,
  'role' : Role,
  'loginCount' : bigint,
  'firstLogin' : Time,
  'lastLogin' : Time,
  'daireId' : [] | [string],
  'binaId' : [] | [bigint],
}
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'loginCount' : bigint,
  'firstLogin' : Time,
  'lastLogin' : Time,
  'daireId' : [] | [string],
  'binaId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'arizaBildir' : ActorMethod<[string, string, string], Ariza>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'binaOlustur' : ActorMethod<[string], bigint>,
  'daireOlustur' : ActorMethod<[string], string>,
  'daireleriListele' : ActorMethod<[], Array<Daire>>,
  'davetKoduOlustur' : ActorMethod<[Role], string>,
  'duyuruOlustur' : ActorMethod<[string, string], Duyuru>,
  'duyurulariListele' : ActorMethod<[], Array<Duyuru>>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'kullaniciBinasiniGetir' : ActorMethod<[], [] | [Bina]>,
  'kullanicilariListele' : ActorMethod<[], Array<UserProfil>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];