/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    role: Role;
    loginCount: bigint;
    firstLogin: Time;
    lastLogin: Time;
    daireId?: string;
    binaId?: bigint;
}
export interface Bina {
    olusturulmaTarihi: Time;
    binaAdi: string;
    olusturanPrincipal: Principal;
    binaId: bigint;
}
export type Time = bigint;
export interface Duyuru {
    olusturmaTarihi: Time;
    baslik: string;
    duyuruId: string;
    aciklama: string;
    olusturanPrincipal: Principal;
    binaId: bigint;
}
export interface UserProfil {
    principal: Principal;
    name: string;
    role: Role;
    loginCount: bigint;
    firstLogin: Time;
    lastLogin: Time;
    daireId?: string;
    binaId?: bigint;
}
export interface Ariza {
    arizaId: string;
    baslik: string;
    olusturmaZamani: Time;
    aciklama: string;
    olusturanPrincipal: Principal;
    daireId: string;
    durum: ArizaDurumu;
    binaId: bigint;
}
export interface Daire {
    olusturmaTarihi: Time;
    daireId: string;
    binaId: bigint;
    daireAdi: string;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export enum ArizaDurumu {
    acik = "acik",
    kapali = "kapali"
}
export enum Role {
    yetkili = "yetkili",
    sakin = "sakin",
    binaSahibi = "binaSahibi"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    arizaBildir(baslik: string, aciklama: string, daireId: string): Promise<Ariza>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    binaOlustur(binaAdi: string): Promise<bigint>;
    daireOlustur(daireAdi: string): Promise<string>;
    daireleriListele(): Promise<Array<Daire>>;
    davetKoduOlustur(yeniRol: Role): Promise<string>;
    duyuruOlustur(baslik: string, aciklama: string): Promise<Duyuru>;
    duyurulariListele(): Promise<Array<Duyuru>>;
    generateInviteCode(): Promise<string>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    kullaniciBinasiniGetir(): Promise<Bina | null>;
    kullanicilariListele(): Promise<Array<UserProfil>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
}
import type { Ariza as _Ariza, ArizaDurumu as _ArizaDurumu, Bina as _Bina, Role as _Role, Time as _Time, UserProfil as _UserProfil, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async arizaBildir(arg0: string, arg1: string, arg2: string): Promise<Ariza> {
        if (this.processError) {
            try {
                const result = await this.actor.arizaBildir(arg0, arg1, arg2);
                return from_candid_Ariza_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.arizaBildir(arg0, arg1, arg2);
            return from_candid_Ariza_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async binaOlustur(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.binaOlustur(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.binaOlustur(arg0);
            return result;
        }
    }
    async daireOlustur(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.daireOlustur(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.daireOlustur(arg0);
            return result;
        }
    }
    async daireleriListele(): Promise<Array<Daire>> {
        if (this.processError) {
            try {
                const result = await this.actor.daireleriListele();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.daireleriListele();
            return result;
        }
    }
    async davetKoduOlustur(arg0: Role): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.davetKoduOlustur(to_candid_Role_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.davetKoduOlustur(to_candid_Role_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async duyuruOlustur(arg0: string, arg1: string): Promise<Duyuru> {
        if (this.processError) {
            try {
                const result = await this.actor.duyuruOlustur(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duyuruOlustur(arg0, arg1);
            return result;
        }
    }
    async duyurulariListele(): Promise<Array<Duyuru>> {
        if (this.processError) {
            try {
                const result = await this.actor.duyurulariListele();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duyurulariListele();
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async kullaniciBinasiniGetir(): Promise<Bina | null> {
        if (this.processError) {
            try {
                const result = await this.actor.kullaniciBinasiniGetir();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kullaniciBinasiniGetir();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async kullanicilariListele(): Promise<Array<UserProfil>> {
        if (this.processError) {
            try {
                const result = await this.actor.kullanicilariListele();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kullanicilariListele();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ArizaDurumu_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArizaDurumu): ArizaDurumu {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Ariza_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ariza): Ariza {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfil_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfil): UserProfil {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bina]): Bina | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
    loginCount: bigint;
    firstLogin: _Time;
    lastLogin: _Time;
    daireId: [] | [string];
    binaId: [] | [bigint];
}): {
    name: string;
    role: Role;
    loginCount: bigint;
    firstLogin: Time;
    lastLogin: Time;
    daireId?: string;
    binaId?: bigint;
} {
    return {
        name: value.name,
        role: from_candid_Role_n12(_uploadFile, _downloadFile, value.role),
        loginCount: value.loginCount,
        firstLogin: value.firstLogin,
        lastLogin: value.lastLogin,
        daireId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.daireId)),
        binaId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.binaId))
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arizaId: string;
    baslik: string;
    olusturmaZamani: _Time;
    aciklama: string;
    olusturanPrincipal: Principal;
    daireId: string;
    durum: _ArizaDurumu;
    binaId: bigint;
}): {
    arizaId: string;
    baslik: string;
    olusturmaZamani: Time;
    aciklama: string;
    olusturanPrincipal: Principal;
    daireId: string;
    durum: ArizaDurumu;
    binaId: bigint;
} {
    return {
        arizaId: value.arizaId,
        baslik: value.baslik,
        olusturmaZamani: value.olusturmaZamani,
        aciklama: value.aciklama,
        olusturanPrincipal: value.olusturanPrincipal,
        daireId: value.daireId,
        durum: from_candid_ArizaDurumu_n3(_uploadFile, _downloadFile, value.durum),
        binaId: value.binaId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    role: _Role;
    loginCount: bigint;
    firstLogin: _Time;
    lastLogin: _Time;
    daireId: [] | [string];
    binaId: [] | [bigint];
}): {
    principal: Principal;
    name: string;
    role: Role;
    loginCount: bigint;
    firstLogin: Time;
    lastLogin: Time;
    daireId?: string;
    binaId?: bigint;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: from_candid_Role_n12(_uploadFile, _downloadFile, value.role),
        loginCount: value.loginCount,
        firstLogin: value.firstLogin,
        lastLogin: value.lastLogin,
        daireId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.daireId)),
        binaId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.binaId))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yetkili: null;
} | {
    sakin: null;
} | {
    binaSahibi: null;
}): Role {
    return "yetkili" in value ? Role.yetkili : "sakin" in value ? Role.sakin : "binaSahibi" in value ? Role.binaSahibi : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    acik: null;
} | {
    kapali: null;
}): ArizaDurumu {
    return "acik" in value ? ArizaDurumu.acik : "kapali" in value ? ArizaDurumu.kapali : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfil>): Array<UserProfil> {
    return value.map((x)=>from_candid_UserProfil_n20(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    loginCount: bigint;
    firstLogin: Time;
    lastLogin: Time;
    daireId?: string;
    binaId?: bigint;
}): {
    name: string;
    role: _Role;
    loginCount: bigint;
    firstLogin: _Time;
    lastLogin: _Time;
    daireId: [] | [string];
    binaId: [] | [bigint];
} {
    return {
        name: value.name,
        role: to_candid_Role_n7(_uploadFile, _downloadFile, value.role),
        loginCount: value.loginCount,
        firstLogin: value.firstLogin,
        lastLogin: value.lastLogin,
        daireId: value.daireId ? candid_some(value.daireId) : candid_none(),
        binaId: value.binaId ? candid_some(value.binaId) : candid_none()
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    yetkili: null;
} | {
    sakin: null;
} | {
    binaSahibi: null;
} {
    return value == Role.yetkili ? {
        yetkili: null
    } : value == Role.sakin ? {
        sakin: null
    } : value == Role.binaSahibi ? {
        binaSahibi: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
